# Generated by Django 3.2.16 on 2025-02-16 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_rename_post_comment_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='post_id',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.post', verbose_name='Номер соответствующего поста'),
            preserve_default=False,
        ),
    ]
