# Generated by Django 3.2.16 on 2025-02-22 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20250222_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.category', verbose_name='Категория'),
        ),
    ]
